name: Swift

on:
  push:
    branches: [ main ]

jobs:
  BuildAndTest:
    runs-on: macos-11.0
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.2'
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
